### ISSUE TITLE
Diagonalization with complex eigenvalues fails 

### ISSUE THREAD

**Issue by Wihtedeka** [mbruno46/pyobs#3]
Diagonalization using `pyobs.linalg.eigLR` fails when the eigenvalues/eigenvectors are complex. For example 
```
mat = np.array([[0.0, -1], [1, 0.0]]) # eigenvalues are +- i
obs = pyobs.observable()
obs.create_from_cov('Ens', mat.flatten(), np.zeros(len(mat.flatten())))
obs = pyobs.reshape(obs, mat.shape)
eigv, legiv, reigv = pyobs.linalg.eigLR(obs) 
``` 
fails with the error 
```
UFuncTypeError                            Traceback (most recent call last)
Cell In[41], line 1
----> 1 eigv, legiv, reigv = pyobs.linalg.eigLR(obs) 
      2 print(eigv)

File ~/pyenv/lib/python3.11/site-packages/pyobs/tensor/linalg.py:157, in eigLR(x)
    154                 gv[:, n] += tmp[m, n] / (l[n] - l[m]) * w[:, m]
    155     return gv
--> 157 gv = pyobs.gradient(gradv, x.mean)
    159 # d w_n = sum_{m \neq n} (v_m, dA^T w_n) / (l_n - l_m) v_m
    160 def gradw(y):

File ~/pyenv/lib/python3.11/site-packages/pyobs/core/gradient.py:36, in gradient.__init__(self, g, x0, gtype)
     33     self.grad = g
     34     return
---> 36 self.Na = numpy.size(g(x0))
     37 self.Ni = numpy.size(x0)
     38 self.gtype = gtype

File ~/pyenv/lib/python3.11/site-packages/pyobs/tensor/linalg.py:154, in eigLR.<locals>.gradv(y)
    152     for m in range(x.shape[1]):
    153         if n != m:
--> 154             gv[:, n] += tmp[m, n] / (l[n] - l[m]) * w[:, m]
    155 return gv

UFuncTypeError: Cannot cast ufunc 'add' output from dtype('complex128') to dtype('float64') with casting rule 'same_kind'
```
This can be fixed by e.g. defining `gv = numpy.zeros(x.shape, dtype=numpy.complex128)` instead, but in the subsequent calls to `pyobs.gradient` arrays of floats are explicitly used in the `__init__` call. 

How to work with generic matrix observables, which are bound to have complex eigenvalues?

**Comment by mbruno46** [comment]
@Wihtedeka thanks for your feedback! 

`pyobs` at the moment supports only real observables, so any function returning complex values will fail if applied to a `pyobs.observable`.
I had a private branch with a patch for complex matrices which I have now pushed into the master, but you have to keep in mind that this feature is temporary, subject to syntax changes and may not be supported in future versions.  

Nevertheless, now you should be able to do this
```python
mat1 = np.array([[0.0, -1.0], [1, 0.0]])
obs1 = pyobs.observable()
obs1.create_from_cov('a', mat1, np.array([0.0, 0.01, 0.02, 0.0]))

mat2 = np.array([[2.0, -1.0], [1, 0.0]])
obs2 = pyobs.observable()
obs2.create_from_cov('b', mat2, np.array([0.05, 0.01, 0.02, 0.0]))

cobs = pyobs.complex_observable(real=obs1, imag=obs2)
print(cobs)

w, v = cobs.eig()
print(w)
print(w.real)
print(w.imag)
```
which returns
```
0	-1.00(10)
1.00(14)	0

2.00(22)	-1.00(10)
1.00(14)	0

-0.786(76)	0.786(88)

2.27(18)	-0.272(84)

-0.786(76)	0.786(88)

2.27(18)	-0.272(84)
```

**Comment by Wihtedeka** [comment]
Hi, thank you so much. Just fyi with the latest stable numpy version 1.26.4 `numpy.lingalg.eig`  returns a named tuple `numpy.linalg.linalg.EigResult`, so for the code to work on a fresh install I had to change line 159 in _core/complex.py_ from `return self.unary_derobs(lambda x: np.linalg.eig(x), [gw, gv])` to e.g. `return self.unary_derobs(lambda x: list(np.linalg.eig(x)), [gw, gv])`.
