### ISSUE TITLE
Slicing [::-1] only reverses the means, not the errors

### ISSUE THREAD

**Issue by Wihtedeka** [mbruno46/pyobs#4]
As the title says. E.g. `reversed_obs = obs[::-1]` only reverses the means, but leaves the errors in place, such that `reversed_obs.mean[0] == obs.mean[-1]` but `reversed_obs.error()[1][0] == obs.error()[1][0]`.

**Comment by mbruno46** [comment]
@Wihtedeka thanks for your feedback and apologies for the long time it took, to get back to this issue. The problem should be fixed now in the new version.
